
app: bookmytble

appName: bmt-be

appType: backend

infraEnv: dev

namespace: default

replicas: 5

image:
  name: libintomdocker/bookmytable-backend
  tag: latest

configmap: 
  name: configmap-bmt-be
  data:
    POSTGRES_HOST: bmt-pgsql
    POSTGRES_PASSWORD: postgres123

services:
  spec:
    ports:
      port: 8005
      targetPort: 8005