apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
spec:
  selector:
    matchLabels:
      app: mongo-sts
  serviceName: "mongo"
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-sts
    spec:
      containers:
      - name: mongo-sts
        image: mongo:4.0.8
        livenessProbe:
          
        args: ["--dbpath", "/data/db"]
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "password"
        command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
