---
# - name: Database Setup
#   hosts: dbservers
#   remote_user: root
#   roles:
#     - common
#     - database

# - name: Webserver Setup
#   hosts: webservers
#   remote_user: root
#   roles:
#     - common
#     - web
- name: Host Prep
  hosts: all
  remote_user: root
  roles:
    - common
    - prephost

- name: Install web app
hosts: all
remote_user: root
roles:
  - webapp