---

- name: Install EPEL (EL)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install packages
  yum:
    name: 
      #- python3-pip
      #- python3-devel
      - python-setuptools
      - nginx
      - gcc
      - policycoreutils-python
    state: present
    update_cache: yes

- name: Install uwsgi
  pip:
    name: uwsgi
    virtualenv: /home/appuser/ve-app
    #executable: pip3


- name: Install requirements in virtualenv
  pip:
    requirements: /home/appuser/app/requirements.txt
    virtualenv: /home/appuser/ve-app
