user_name = input("Enter your name: ")
user_inp1 = int(input("Enter a number: "))
user_inp2 = int(input("Enter another number: "))
print("Hello", user_name, end=" ")
print("Your total number is", user_inp1 + user_inp2)