version: "3.1"
services:
  bookmytable-frontend:
    image: libintomdocker/bookmytable-frontend:latest
    ports:
      - 8000:8000
    environment:
      - BACKEND_URL=http://bmt-be:8005/api
    depends_on:
      - "bookmytable-backend"

  bookmytable-backend:
    container_name: bmt-be
    image: libintomdocker/bookmytable-backend:latest
    ports:
      - 8005:8005
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_HOST=bmt-postgres
    depends_on:
      - "bookmytable-postgres"

  bookmytable-postgres:
    container_name: bmt-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=bmtbkenddb1

secrets:
   db_password:
     file: bmt-postgres-secret.txt