apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /prometheus
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
    # jenkins: slave
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000