# Generated by Django 2.1.15 on 2023-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=50)),
                ('is_classrep', models.BooleanField(default=False, verbose_name='Classrep')),
            ],
        ),
    ]
