apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.app}}
    appname: {{ .Values.appName}}
    app-type: {{ .Values.appType}}
    environment: {{ .Values.infraEnv}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      appname: {{ .Values.appName}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: {{ .Values.appName}}
    spec:
      containers:
      - image: "{{ .Values.image.name}}:{{ .Values.image.tag}}"
        imagePullPolicy: Always
        name: {{ .Values.appName}}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name}}
      restartPolicy: Always