apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bmt-fe
    app-type: frontend
    environment: dev
  name: bmt-fe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmt-fe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bmt-fe
    spec:
      containers:
      - image: libintomdocker/bookmytable-frontend
        imagePullPolicy: Always
        name: bmt-fe
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bmt-fe
    app-type: frontend
    environment: dev
  name: bmt-fe
  namespace: default
spec:
  ports:
  - nodePort:
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: bmt-fe
  sessionAffinity: None
  type: NodePort