apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: bmt-ns
  name: vault-static-secret-libinsecret
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: data/k8s/libinsecret
  refreshAfter: 10s
  destination:
    create: true
    name: libinsecret
  rolloutRestartTargets:
  - kind: Deployment
    name: bmt-fe
