- name: start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
  become: yes
  notify:
    - reload firewalld


- name: Enable traffic port
  firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled
  become: yes

- name: Enable SSh
  firewalld:
    zone: public
    port: 22/tcp
    permanent: true
    state: enabled
  become: yes

- name: Reload Firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  become: yes


