apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: voting
  label:
    name: pgsql-service
    app: voting-app
    comp: pgsql
    env: db
    
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: pgsql-pod
    app: voting-app
    comp: pgsql
    env: db
