apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: voting
  labels:
    name: redis-pod
    app: voting-app
    comp: redis
    env: db
    
spec:
  containers:
    - name: redis-pod
      image: redis
      ports:
        - containerPort: 6379