apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting
  labels:
    name: result-service
    app: voting-app
    comp: result
    env: result-service
    
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    name: result-pod
    app: voting-app
    comp: result
    env: front-end