apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  namespace: voting
  labels:
    name: result-pod
    app: voting-app
    comp: result
    env: front-end
    
spec:
  containers:
    - name: result
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80