apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: voting
  labels:
    name: voting-service
    app: voting-app
    comp: voting
    env: voting-service
    
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: voting-pod
    app: voting-app
    comp: voting
    env: front-end