apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  namespace: voting
  labels:
    name: voting-pod
    app: voting-app
    comp: voting
    env: front-end
    
spec:
  containers:
    - name: voting-pod
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
          hostPort: 80