apiVersion: v1
kind: Pod
metadata:
  name: worker
  namespace: voting
  labels:
    name: worker-pod
    app: voting-app
    comp: worker
    env: back-end
    
spec:
  containers:
    - name: worker-pod
      image: kodekloud/examplevotingapp_worker:v1